metatag.metatag_tag.abstract:
  type: label
  label: 'Abstract'
metatag.metatag_tag.canonical_url:
  type: label
  label: 'Canonical URL'
metatag.metatag_tag.content-language:
  type: label
  label: 'Content Language'
metatag.metatag_tag.description:
  type: label
  label: 'Description'
metatag.metatag_tag.fb_admins:
  type: label
  label: 'Facebook Admins'
metatag.metatag_tag.fb_app_id:
  type: label
  label: 'Facebook App ID'
metatag.metatag_tag.generator:
  type: label
  label: 'Generator'
metatag.metatag_tag.image_src:
  type: label
  label: 'Image SRC'
metatag.metatag_tag.keywords:
  type: label
  label: 'Keywords'
metatag.metatag_tag.news_keywords:
  type: label
  label: 'Google News Keywords'
metatag.metatag_tag.original_source:
  type: label
  label: 'Original source'
metatag.metatag_tag.rights:
  type: label
  label: 'Rights'
metatag.metatag_tag.referrer:
  type: label
  label: 'Referrer policy'
metatag.metatag_tag.robots:
  type: label
  label: 'Robots'
metatag.metatag_tag.shortlink:
  type: label
  label: 'Shortlink'
metatag.metatag_tag.standout:
  type: label
  label: 'Standout'
metatag.metatag_tag.title:
  type: label
  label: 'Page title'
