databases:
  default:
    default:
      database: campaign
      username: root
      password: root
      prefix:
      host: mysql
      port:
      namespace: Drupal\Core\Database\Driver\mysql
      driver: mysql

settings:
  update_free_access: FALSE
  skip_permissions_hardening: TRUE
  rabbitmq_credentials:
    host: 127.0.0.1
    vhost: /
    port: 5672
    username: guest
    password: guest
  queue_service_esu: queue.rabbitmq
  hash_salt: kzWT4Q5kJe2DkfS72PrATBUfkw54RKzMCbQg933K1Qwe0ZKtonOV_xdmuCac
  file_chmod_directory: 0775
  file_chmod_file: 0664
  trusted_host_patterns: ['^campaign\.dev$', '^campaign\.lab$', '^campaign\.local$', '^127\.0\.0\.1$', '^localhost$']

config:
  system.performance:
    css:
      preprocess: false
    js:
      preprocess: false
  system.logging:
    error_level: verbose

config_dir: 'sites/default/config'
